package co.edu.uniquindio.compilador.Analizador_Lexico

/**
 *ESta clase representa todas las categorias de los tokens validos del lenguaje
 */
enum class Categoria {
    ENTREO,
    DECIMAL,
    IDENTIFICADOR,
    OPERADOR_MATEMATICO,
    OPERADOR_LOGICO,
    OPERADOR_RELACIONAL,
    OPERADOR_ASIGNACION,
    DESCONOCIDO,
    COMENTARIO_BLOQUE,
    COMENTARIO_LINEA,
    ERROR,
    CADENA,
    SEPARADOR_COMA,
    PALABRA_RESERVADA,
    PARENTESIS_DERECHO,
    PARENTESIS_IZQUIERDO,
    CORCHETE_DERECHO,
    CORCHETE_IZQUIERDO,
    LLAVE_DERECHA,
    LLAVE_IZQUIERDA,
    OPERADOR_INCREMENTO,
    OPERADOR_DECREMENTO,
    CARACTER,
    FIN_SENTENCIA,
    SIGNO
}